import Head from 'next/head';

function Header() {
  return (
    <Head>
      <title>Rosanno Portfolio</title>
      <meta name='description' content='Generated by create next app' />
      <link rel='icon' href='/icons/favicon.ico' />
    </Head>
  );
}

export default Header;
